version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/nas-01/Applications/gitlab/data:/var/opt/gitlab
      - /mnt/nas-01/Applications/gitlab/logs:/var/log/gitlab
      - /mnt/nas-01/Applications/gitlab/config:/etc/gitlab
    environment:
    #   GITLAB_OMNIBUS_CONFIG: "from_file('/configs/gitlab_omnibus_config.rb')"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://home.mikemay.io'
        gitlab_rails['lfs_enabled'] = true
    # configs:
    #   - source: gitlab
    #     target: /omnibus_config.rb
    # secrets:
    #   - gitlab_root_password
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
    - ./configs/gitlab_runner_config.toml:/etc/gitlab-runner/config.toml
    deploy:
      mode: replicated
      replicas: 4
configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt