---
version: "3.6"
services:
  envoy-frontend:
    image: envoyproxy/envoy:v1.13.1
    networks:
      -  homelab
    hostname: envoy
    volumes:
      - ./configs/envoy/frontend.yaml:/etc/envoy/envoy.yaml
      - ./assets/global/${REALM_NAME}.crt:/etc/${REALM_NAME}.crt
      - ./assets/global/${REALM_NAME}.key:/etc/${REALM_NAME}.key
    expose:
      - "80"
      - "443"
      - "8001"
      - "9901"
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"
      - "9901:9901"

  postgres:
    image: timescale/pg_prometheus:latest-pg11
    networks:
      -  homelab
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "data-postgres:/var/lib/postgresql/data"
      - "./assets/postgres/init-scripts:/docker-entrypoint-initdb.d"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  keycloak:
    image: jboss/keycloak:9.0.2
    networks:
      - homelab
    hostname: keycloak
    expose:
      - "8080"
    depends_on: 
      - postgres
    environment:
      KEYCLOAK_IMPORT: /tmp/realm-${REALM_NAME}.json
      SERVICE_NAME: keycloak
      KEYCLOAK_FRONTEND_URL: https://sso.${DOMAIN_NAME}/auth
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD_FILE: /run/secrets/keycloak_keycloak_password
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    volumes:
      - "./assets/keycloak/realm-${REALM_NAME}.json:/tmp/realm-${REALM_NAME}.json"
    secrets:
      - keycloak_keycloak_password
  
  prometheus:
    depends_on: 
      - postgres
    image: prom/prometheus
    networks:
      - homelab
    ports:
        - "9090:9090"
    volumes:
        - "./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  prometheus_postgresql_adapter:
    depends_on: 
      - postgres
    image: timescale/prometheus-postgresql-adapter:latest
    networks:
      - homelab
    hostname: prometheus_postgresql_adapter
    expose: 
      - "9201"
    command: ['-pg-host=postgres', '-pg-password=password', '-pg-prometheus-log-samples']

  telegraf:
    depends_on: 
      - prometheus
    image: telegraf:1.14
    networks: 
      - homelab
    hostname: telegraf
    volumes:
      - "./configs/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/etc:/host/etc:ro"
      - "/var:/host/var:ro"
      - "/run:/host/run:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /host/etc 
      HOST_VAR: /host/var
      HOST_RUN: /host/run
      HOST_MOUNT_PREFIX: /host

  grafana:
    image: grafana/grafana
    networks: 
      - homelab
    hostname: grafana
    expose: 
      - "3000"
    volumes:
      - "./configs/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./assets/grafana/dashboards:/var/lib/grafana/dashboards"
      - "./assets/grafana/provisioning:/etc/grafana/provisioning"
      - "./assets/global/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
    environment: 
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,monasca-datasource,grafana-kubernetes-app
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
  
  mattermost:
    build:
      context: contexts/mattermost
      args:
        - edition=team
    networks: 
      - homelab
    hostname: mattermost
    expose: 
      - "8000"
    volumes:
      - data-mattermost:/mattermost:rw
      - ./configs/mattermost/config.json:/mattermost/config/config.json:rw
      - /etc/localtime:/etc/localtime:ro
      - "./assets/global/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      MM_DBNAME: mattermost
      MM_USERNAME: mattermost
      MM_PASSWORD: mattermost
      SERVICE_NAME: mattermost
  
networks:
  homelab:
    driver: bridge

volumes:
  data-postgres:
  data-mattermost:

secrets:
  keycloak_keycloak_password:
    file: ./password_files/keycloak.keycloak.password.txt
  grafana_admin_password:
    file: ./password_files/grafana.admin.password.txt