global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: 
      - telegraf:9273
  - job_name: nginx
    static_configs:
    - targets:
      - gitlab:8060
  - job_name: redis
    static_configs:
    - targets:
      - gitlab:9121
  - job_name: postgres
    static_configs:
    - targets:
      - gitlab:9187
  - job_name: node
    static_configs:
    - targets:
      - gitlab:9100
  - job_name: gitlab-workhorse
    static_configs:
    - targets:
      - gitlab:9229
  - job_name: gitlab-rails
    metrics_path: "/-/metrics"
    static_configs:
    - targets:
      - gitlab:8080
  - job_name: gitlab-sidekiq
    static_configs:
    - targets:
      - gitlab:8082
  - job_name: gitlab_exporter_database
    metrics_path: "/database"
    static_configs:
    - targets:
      - gitlab:9168
  - job_name: gitlab_exporter_sidekiq
    metrics_path: "/sidekiq"
    static_configs:
    - targets:
      - gitlab:9168
  - job_name: gitlab_exporter_process
    metrics_path: "/process"
    static_configs:
    - targets:
      - gitlab:9168
  - job_name: gitaly
    static_configs:
    - targets:
      - gitlab:9236
remote_write:
  - url: "http://prometheus_postgresql_adapter:9201/write"
remote_read:
  - url: "http://prometheus_postgresql_adapter:9201/read"