---
foreman:
  apache: true
  configure_epel_repo: true
  configure_scl_repo: true
  initial_admin_username: admin
foreman_proxy: {}
puppet:
  server: true
foreman::cli: true
foreman::cli::ansible: true
foreman::cli::azure: false
foreman::cli::discovery: true
foreman::cli::openscap: true
foreman::cli::remote_execution: true
foreman::cli::tasks: true
foreman::cli::templates: true
foreman::cli::kubevirt: true
foreman::plugin::ansible: true
foreman::plugin::azure: false
foreman::plugin::bootdisk: true
foreman::plugin::chef: false
foreman::plugin::default_hostgroup: true
foreman::plugin::dhcp_browser: true
foreman::plugin::digitalocean: false
foreman::plugin::discovery: true
foreman::plugin::expire_hosts: true
foreman::plugin::kubevirt: true
foreman::plugin::host_extra_validator: false
foreman::plugin::memcache: false
foreman::plugin::monitoring: true
foreman::plugin::omaha: false
foreman::plugin::openscap: true
foreman::plugin::ovirt_provision: true
foreman::plugin::tasks: true
foreman::plugin::hooks: true
foreman::plugin::puppetdb: false
foreman::plugin::remote_execution: true
foreman::plugin::remote_execution::cockpit: false
foreman::plugin::salt: false
foreman::plugin::setup: true
foreman::plugin::snapshot_management: false
foreman::plugin::templates: true
foreman::compute::ec2: false
foreman::compute::gce: false
foreman::compute::libvirt: true
foreman::compute::openstack: true
foreman::compute::ovirt: true
foreman::compute::rackspace: false
foreman::compute::vmware: true
foreman_proxy::plugin::ansible: true
foreman_proxy::plugin::chef: false
foreman_proxy::plugin::dhcp::infoblox: false
foreman_proxy::plugin::dhcp::remote_isc: true
foreman_proxy::plugin::discovery: true
foreman_proxy::plugin::dns::infoblox: false
foreman_proxy::plugin::dns::powerdns: true
foreman_proxy::plugin::dynflow: false
foreman_proxy::plugin::monitoring: true
foreman_proxy::plugin::omaha: false
foreman_proxy::plugin::openscap: true
foreman_proxy::plugin::pulp: true
foreman_proxy::plugin::remote_execution::ssh: true
foreman_proxy::plugin::salt: false